import type { Metadata } from 'next';
import './globals.css';
import { inter, parkinsans, questrial } from '@/lib/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${parkinsans.className} ${questrial.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
